# Numpy practice

In [1]:
import numpy as np


In [3]:
import warnings
warnings.filterwarnings("ignore")



In [ ]:
# Basics

In [4]:
list1 = [7,8,9,1,2,3,4,5]

In [5]:
arr_1 = np.array(list1)

In [7]:
arr_1

array([7, 8, 9, 1, 2, 3, 4, 5])

In [11]:
type(arr_1)

numpy.ndarray

In [12]:
arr_1.dtype

dtype('int32')

In [13]:
arr_1.astype(float)

array([7., 8., 9., 1., 2., 3., 4., 5.])

In [15]:
np.round(arr_1)

array([7, 8, 9, 1, 2, 3, 4, 5])

In [16]:
len(arr_1)

8

In [17]:
arr_1.size

8

In [18]:
arr_1.ndim

1

In [19]:
# arrange

In [21]:
np.arange(7,14)

array([ 7,  8,  9, 10, 11, 12, 13])

In [23]:
np.arange(7,70,7)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63])

In [24]:
np.repeat(7,5)

array([7, 7, 7, 7, 7])

In [26]:
a = np.array([1,2,3])
np.repeat(a,5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3])

In [28]:
b = np.arange(5,20)
b[b%2 ==1]

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [29]:
b = np.arange(5,20)
b[b%2 ==0]

array([ 6,  8, 10, 12, 14, 16, 18])

In [30]:
#linear space

In [31]:
np.linspace(50,200,4)

array([ 50., 100., 150., 200.])

In [32]:
# Random no.

In [33]:
np.random.random(10)

array([0.66308884, 0.33401941, 0.73287289, 0.37093411, 0.46890574,
       0.77972139, 0.6170868 , 0.90936205, 0.12346839, 0.29486366])

In [36]:
np.random.randint(0,100,10)

array([94,  7,  3, 38, 70, 93, 14, 57, 42, 24])

In [37]:
np.random.seed(1)
np.random.randint(0,50,7)

array([37, 43, 12,  8,  9, 11,  5])

In [38]:
np.random.seed(1)
np.random.randint(0,50,7)

array([37, 43, 12,  8,  9, 11,  5])

In [42]:
a1 = np.random.uniform(7,20, size=(10))

In [43]:
a1


array([ 8.20040173,  9.42138275, 11.49228945, 12.15797716, 14.00461754,
       12.44952869, 15.90785351,  9.65787925, 18.41552667,  7.35603871])

In [48]:
b1 = np.random.randn(10,5)

In [49]:
b1

array([[ 0.27803408,  0.69003169, -0.91797604, -0.85183742,  0.09075857],
       [ 1.16220247,  0.32178247,  1.34131783,  0.14167518,  1.73738467],
       [ 0.37576878,  1.47825568, -2.08016719, -0.45342757, -0.17899462],
       [-0.6331164 ,  0.47462717, -0.48456301,  0.37588444,  0.74804848],
       [-1.18845766,  0.24361123, -2.0972406 , -0.44863063,  0.47055959],
       [-1.39857823,  0.5488829 , -0.24751502, -0.22512748,  0.37969188],
       [-0.11569475, -0.1466201 ,  1.76939854, -0.00321878, -0.66646013],
       [-0.77183601, -0.26496068,  1.10728223, -1.34873652,  0.59090275],
       [ 0.03795507, -0.95272402, -1.20102365, -0.07904398,  0.78989335],
       [ 2.18617751, -0.926691  ,  0.40184526, -0.79589304,  0.72023249]])

In [50]:
# operations on arrays

In [51]:
arr_1

array([7, 8, 9, 1, 2, 3, 4, 5])

In [53]:
arr_1.sum()

39

In [54]:
arr_1.cumsum()

array([ 7, 15, 24, 25, 27, 30, 34, 39], dtype=int32)

In [56]:
arr_1.mean()

4.875

In [58]:
np.median(arr_1)

4.5

In [59]:
np.var(arr_1)

7.359375

In [60]:
np.std(arr_1)

2.7128168017763383

In [66]:
# n-dimensional array

In [68]:
arr_2 = np.array([[1,2,3,4] ,[4,5,6,7] ,[8,9,5,3] ,[2,7,8,5]])

In [69]:
arr_2

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [8, 9, 5, 3],
       [2, 7, 8, 5]])

In [70]:
np.amin(arr_2, axis=1)

array([1, 4, 3, 2])

In [71]:
np.amin(arr_2, axis=0)

array([1, 2, 3, 3])

In [73]:
for index, value in np.ndenumerate(arr_2):
    print(index,value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 5
(2, 3) 3
(3, 0) 2
(3, 1) 7
(3, 2) 8
(3, 3) 5


In [76]:
arr_2[1]

array([4, 5, 6, 7])

In [77]:
arr_2[1,2]

6

In [79]:
rep1 = np.where(arr_2%2 == 1, 0, arr_2)
rep1

array([[0, 2, 0, 4],
       [4, 0, 6, 0],
       [8, 0, 0, 0],
       [2, 0, 8, 0]])

In [82]:
rep2 = np.put(arr_2, [0], [7,9,6])
rep2

In [83]:
rep2

In [88]:
np.isnan(arr_1)

array([False, False, False, False, False, False, False, False])

In [89]:
np.where(np.isnan(arr_1))

(array([], dtype=int64),)

In [91]:
np.vstack([arr_1,arr_1])

array([[7, 8, 9, 1, 2, 3, 4, 5],
       [7, 8, 9, 1, 2, 3, 4, 5]])

In [93]:
np.vstack([np.arange(0,8),arr_1])

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [7, 8, 9, 1, 2, 3, 4, 5]])

In [95]:
np.hstack([np.arange(0,8),arr_1])

array([0, 1, 2, 3, 4, 5, 6, 7, 7, 8, 9, 1, 2, 3, 4, 5])

In [97]:
np.intersect1d(arr_1,arr_2)

array([2, 3, 4, 5, 7, 8, 9])

In [98]:
np.setdiff1d(arr_1,arr_2)

array([1])

In [99]:
np.where(arr_1==arr_2)

(array([], dtype=int64),)

In [100]:
c = np.arange(0,30,3)

In [102]:
c[np.where((c>7) & (c<27))]

array([ 9, 12, 15, 18, 21, 24])

In [109]:
np.isin(c, [9,4])

array([False, False, False,  True, False, False, False, False, False,
       False])

In [ ]:
# reverse rows and columns

In [110]:
arr_2[::-1]

array([[2, 7, 8, 5],
       [8, 9, 5, 3],
       [4, 5, 6, 7],
       [7, 9, 6, 4]])

In [111]:
arr_2[:,::-1]

array([[4, 6, 9, 7],
       [7, 6, 5, 4],
       [3, 5, 9, 8],
       [5, 8, 7, 2]])

In [113]:
arr_2[::-1,::-1]

array([[5, 8, 7, 2],
       [3, 5, 9, 8],
       [7, 6, 5, 4],
       [4, 6, 9, 7]])